global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'auction-api'
    static_configs:
      - targets: ['host.docker.internal:5001'] # hard-coded port matches launchSettings.json
  - job_name: 'search-api'
    static_configs:
      - targets: [ 'host.docker.internal:5004' ] # hard-coded port matches launchSettings.json