name: auction service ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # Publish the application as a Docker image
      - name: Create Docker Image
        run: dotnet publish "src/Auction.API/Auction.API.csproj" -t:PublishContainer --verbosity "quiet" --nologo -r "linux-arm64" -p:ContainerRepository="duynguyenbui/auction-api" -p:ContainerImageTag="latest"

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Push the Docker image to the repository
      - name: Docker Push
        run: docker push duynguyenbui/auction-api:latest
