name: webapp service ci

on:
  workflow_dispatch:

env:
  REGISTRY_IMAGE: duynguyenbui/webapp
  DOCKERFILE: src/webapp/Dockerfile
  DEPLOYMENT_NAME: webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
